import {CreditTypes, DebitTypes} from "@/balance";
import Colors from "@/colors";

export const defaultColorMappings = {
    [DebitTypes.cash]: Colors.green,
    [DebitTypes.backAccount]: Colors.blue,
    [DebitTypes.property]: Colors.purple,
    [DebitTypes.loan]: Colors.lightPurple,
    [DebitTypes.noneMoney]: Colors.white,
    [DebitTypes.nonMoneyHouse]: Colors.white,
    [DebitTypes.none]: Colors.grey,
    [DebitTypes.mlPossessions]: Colors.mlAssetPossessions,
    [DebitTypes.mlCentralGold]: Colors.mlAssetCentralGold,
    [DebitTypes.mlCentralForeignCurrencies]: Colors.mlAssetCentralForeignCurrencies,
    [DebitTypes.mlCentralBonds]: Colors.mlAssetCentralBonds,
    [DebitTypes.mlCentralLoansToBanks]: Colors.mlAssetCentralLoansToBanks,
    [DebitTypes.mlCorporateDigitalPublicMoney]: Colors.mlAssetCorporateDigitalPublicMoney,
    [DebitTypes.mlCorporatePhysicalPublicMoney]: Colors.mlAssetCorporatePhysicalPublicMoney,
    [DebitTypes.mlCorporateBonds]: Colors.mlAssetCorporateBonds,
    [DebitTypes.mlCorporateLoansToBanks]: Colors.mlAssetCorporateLoansToBanks,
    [DebitTypes.mlCorporateLoansToNonBanks]: Colors.mlAssetCorporateLoansToNonBanks,
    [CreditTypes.equity]: Colors.blue,
    [CreditTypes.debt]: Colors.red,
    [CreditTypes.creditAccount]: Colors.darkGreen,
    [CreditTypes.reserves]: Colors.green,
    [CreditTypes.currency]: Colors.blue,
    [CreditTypes.deposits]: Colors.red,
    [CreditTypes.newDeposits]: Colors.red,
    [CreditTypes.newLoans]: Colors.white,
    [CreditTypes.none]: Colors.grey,
    [CreditTypes.mlObligations]: Colors.mlLiabilitiesObligations,
    [CreditTypes.mlEquities]: Colors.mlLiabilitiesEquities,
    [CreditTypes.mlCentralDigitalPublicMoney]: Colors.mlLiabilitiesCentralDigitalPublicMoney,
    [CreditTypes.mlCentralPhysicalPublicMoneyInCirculation]: Colors.mlLiabilitiesCentralPhysicalPublicMoneyInCirculation,
    [CreditTypes.mlCentralCapital]: Colors.mlLiabilitiesCentralCapital,
    [CreditTypes.mlCorporateInsuredPrivateMoney]: Colors.mlLiabilitiesCorporateInsuredPrivateMoney,
    [CreditTypes.mlCorporateUninsuredPrivateMoney]: Colors.mlLiabilitiesCorporateUninsuredPrivateMoney,
    [CreditTypes.mlCorporateLoansFromBanks]: Colors.mlLiabilitiesCorporateLoansFromBanks,
    [CreditTypes.mlCorporateLongTermDepths]: Colors.mlLiabilitiesCorporateLongTermDepths,
    [CreditTypes.mlCorporateCapital]: Colors.mlLiabilitiesCorporateCapital,
}
